### ISSUE TITLE
Rails/RelativeDateConstant doesn't understand complex constants and autocorrects incorrectly

### ISSUE THREAD

**Issue by brandonweiss** [rubocop-hq/rubocop#4204]
After upgrading to `0.48.0` I see this offense:

```
spec/billing_spec_helper.rb:59:1: C: Rails/RelativeDateConstant: Do not assign ago to constants as it will be evaluated only once.
STRIPE_EXAMPLE_DATA = { ...
^^^^^^^^^^^^^^^^^^^^^^^
```

The actual code is:

```ruby
STRIPE_EXAMPLE_DATA = {
  customer: OpenStruct.new(
    id: "stripe_customer_id",
  ),
  source: OpenStruct.new(
    id: "card_example",
    last4: "1234",
    brand: "Visa",
    exp_month: 4,
    exp_year: 11,
    fingerprint: "foo",
    country: "US",
  ),
  invoice: OpenStruct.new(
    charge: "charge-1",
  ),
  charge: OpenStruct.new(
    id: "charge-1",
    refunds: [
      OpenStruct.new(
        id: "refund-1",
        created: 1.day.ago.to_i,
        state: "success",
      ),
    ],
  ),
}.freeze
```

And if I autocorrect it I get:

```ruby
def self.stripe_example_data
{
  customer: OpenStruct.new(
    id: "stripe_customer_id",
  ),
  source: OpenStruct.new(
    id: "card_example",
    last4: "1234",
    brand: "Visa",
    exp_month: 4,
    exp_year: 11,
    fingerprint: "foo",
    country: "US",
  ),
  invoice: OpenStruct.new(
    charge: "charge-1",
  ),
  charge: OpenStruct.new(
    id: "charge-1",
    refunds: [
      OpenStruct.new(
        id: "refund-1",
        created: 1.day.ago.to_i,
        state: "success",
      ),
    ],
  ),
}.freeze
end
```

The indentation in the method is incorrect and it didn't update the constant to use the method it had created.

**Comment by rrosenblum** [comment]
> The indentation in the method is incorrect and it didn't update the constant to use the method it had created.

I agree that the indentation should be fixed. 

The constant cannot and should not use the method. The intention is that the method should be used instead of the constant. Using any sort of time in a constant can be dangerous because the time is calculated at the time of class load and not at run time. 

If you were to start a Rails server today (2017-03-29), the constant would contain the date 2017-03-28. If the server stays up until tomorrow (2017-03-30), the constant would still contain the date 2017-03-28. 
The impact is worse with things like Passenger or Puma that most likely are configured to run multiple instances of the application in different processes and spawn and kill processes over time. Since different processes will have different start times, the constant could contain different values based on which instance of the application gets hit.

This doesn't seem like the kind of thing that we normally implement auto-correct for since the correction would could leave broken code.

**Comment by brandonweiss** [comment]
🤦🏼‍♂️ Of course, if the constant used the method it would be the same problem, just shifted around. I agree… I don't think this is something that can be auto-corrected.

**Comment by bbatsov** [comment]
We're in the process of moving all Rails-related functionality to a standalone library (gem) named `rubocop-rails`. Please, migrate this issue to its issue tracker https://github.com/rubocop-hq/rubocop-rails/issues/
