### ISSUE TITLE
Should Performance cops be disabled by default?

### ISSUE THREAD

**Issue by Drenmi** [rubocop-hq/rubocop#5169]
I have been thinking about this for a few weeks, and would like to get some thoughts on it.

Some reasons I consider for having the performance cops disabled by default:

1. Language level micro optimisations are tightly coupled to low level implementation details in MRI and YARV. Something that is faster in version X may just be slower in version Y. This becomes more relevant as work with Ruby 3x3 progresses.

2. Most of the performance optimisations make a trade-off by making the code less readable or understandable, which runs contrary to RuboCop's overall mission. IMO these trade-offs should be made in response to an observed problem, and after careful deliberation, rather than by default.

For me, the ideal solution would be to have these in a separate project, maintained by someone who has a specific interest in it, but there's overhead in setting that up, and I don't know if such a person exists. 🙂

**Comment by bbatsov** [comment]
> For me, the ideal solution would be to have these in a separate project, maintained by someone who has a specific interest in it, but there's overhead in setting that up, and I don't know if such a person exists. 🙂

Yeah, I agree. Same applies to the Rails cops as well, btw. I'm guessing the real problem that needs solving is making extensions painless to create and the rest would naturally solve itself.

**Comment by rrosenblum** [comment]
I feel like this is an over generalization of the performance cops. I agree that several should not be enabled by default because of the trade off with readability and the potential to be version specific. Some of the cops are going to be valuable regardless of Ruby version (examples: `DoublStartEndWith`, `CaseWhenSplat`, `FixedSize`, `Sample`). 

> I'm guessing the real problem that needs solving is making extensions painless to create and the rest would naturally solve itself.

I was thinking about this a little bit the other day. We could extract the core functionality out into `rubocop-core`. All cop types could be their own gem (`rubocop-style`, `rubocop-lint`, ...). The `rubocop` gem itself could then live as a meta gem that loads in `rubocop-core`, `rubocop-style` and the other cops that we consider core.

**Comment by Drenmi** [comment]
> Some of the cops are going to be valuable regardless of Ruby version.

An interesting follow up question then, is whether they should be in `Performance` at all. 🙂 At best, they incidentally lead to better performance, at worst, they are mislabeled `Style` cops.

I guess it's easier to reason about now, if we consider splitting them out. Would we want them to remain in core if doing so?

**Comment by rrosenblum** [comment]
> An interesting follow up question then, is whether they should be in `Performance` at all. 🙂 At best, they incidentally lead to better performance, at worst, they are mislabeled `Style` cops.

I think classifying them as `Performance` is important because it explains what they actually do. We just moved several cops from `Style` to `Layout` for a similar reason. It is hard to justify that using `casecmp` (`str.casecmp('ABC').zero?`) is stylistically better than `upcase` or `downcase` (`str.downcase == 'abc'`). It is much easier to justify the use of `casecmp` for performance though.

**Comment by Darhazer** [comment]
I believe extracting the performance cops into [separate gem](5977) resolves the question

**Comment by bbatsov** [comment]
Yep.
