### ISSUE TITLE
Implement options to run only safe cops and safe auto-corrects

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop#5980]
That's a continuation of #5978. Once we know which cops are safe it'd be trivial do the following:

* add a command line switch --safe to run only safe cops
* add a command line switch --safe-auto-correct to run only safe auto-corrections
* Add some config options to enable safe cops/safe auto-corrections through `.rubocop.yml`

**Comment by perlun** [comment]
Good idea. I would even go as far as to say that `--safe` and `--safe-auto-correct` should be the default, so that potentially "unsafe" cops & auto-corrections are disabled by default. Less noise from people running them by mistake; people who really want these cops are usually clever enough to figure out how to enable them anyway. 😉

**Comment by bbatsov** [comment]
Perhaps. On the other hand that'd be a departure from the current behaviour and it would certainly surprise a few people. Let's implement the metadata and the options firsts, changing the defaults is easy afterwards. 😄

**Comment by bbatsov** [comment]
@Darhazer I guess it makes sense for you to reap the benefits of your work on the huge metadata tasks, so I'm assigning this to you.
