### ISSUE TITLE
Updating to dynamic attributes - error

### ISSUE THREAD

**Issue by mellansquare** [rubocop-hq/rubocop#6381]
Hi,

I'm super new to ruby on rails so I apologise for my lack of knowledge from the start.  I have tried running the commands that come up to update rubocop to dynamic attributes (which come up when I run a test).  An error is occuring and this is the info that comes up and told me to report to you:

Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
0.59.2 (using Parser 2.5.1.2, running on ruby 2.3.4 x86_64-linux)

**Comment by mikegee** [comment]
Since you mention "dynamic attributes" I think you're referring to the [`FactoryBot/AttributeDefinedStatically` cop](https://github.com/rubocop-hq/rubocop-rspec/pull/666). Does the documentation at https://thoughtbot.com/blog/deprecating-static-attributes-in-factory_bot-4-11 help resolve your problem?
