### ISSUE TITLE
rubocop -a is slow

### ISSUE THREAD

**Issue by gurgeous** [rubocop-hq/rubocop#6492]
See https://github.com/ruby-formatter/rufo/issues/2 and https://github.com/Microsoft/vscode/issues/41194. It is not really possible to use Rubocop autocorrect in vscode unless the user manually increases the `editor.formatOnSaveTimeout`. I have mine set to 3s, which seems to be sufficient for my app on my beefy machine. I bet if we sped up Rubocop autocorrect, many more people would adopt it for vscode Format on Save.

Here's a simple benchmark:

```
$ wget https://raw.githubusercontent.com/rails/rails/master/actionpack/lib/action_controller/metal/strong_parameters.rb
$ time rubocop -a strong_parameters.rb
Inspecting 1 file
...
1 file inspected, 118 offenses detected, 114 offenses corrected

real	0m3.087s
user	0m2.853s
sys	0m0.194s
```

I have 43 cops disabled in my .rubocop.yml, so the vanilla config might be slower. Thanks so much for all your hard work on Rubocop. I love it and use it daily with all my projects!

**Comment by Drenmi** [comment]
I'll try to provide some insight into why this is slow. Part of it is startup time. Parsing configuration, etc. Part is RuboCop currently works by using what we call the "correction loop". As soon as we rewrite part of a file, we have all cops re-inspect that file, since the correction may have caused violations that can be picked up by other cops.

So when your file has 114 correctable offenses, we will have all cops inspect the file 115 times. I assume the biggest problem will be on the first run. I haven't given much thought to how this could be done differently, but there might be better ways.

**Comment by bbatsov** [comment]
Yeah, that's a great overview of the problem and we should really investigate where exactly we spend so much time and how can we optimize the performance. Past experience has taught me that when we put our focus in this direction we can achieve some epic performance boosts. :-)

**Comment by gurgeous** [comment]
I am completely unfamiliar with the rubocop source, but I noticed that `RuboCop::Runner#do_inspection_loop` runs the cops 12 times on the `strong_parameters.rb` test file referenced above. Is that amount of looping common?

**Comment by jonas054** [comment]
@gurgeous I'm not sure how common it is, but I think it's expected. Some cops rewrite the code so that new offenses are generated. I've looked at what happens during auto-correction of `strong_parameters.rb`, and it looks like the `Layout/CommentIndentation` cop is especially to blame for the long running time of `rubocop -a`. The cop corrects one line at a time and writes that change to file. If there's a preceding comment line that originally had the same indentation as the corrected line, that line now has an offense, which will be corrected in the next run. And so on.

If the indentation cops could look at the surrounding lines and fix them too when they see that there will be new offenses in the next iteration, I think we could take big steps towards shorter auto-correction times.

**Comment by gurgeous** [comment]
I see, thank you for clarifying. I wonder if we should also target the *second* rubocop run, since that mirrors real world usage when plugged into an editor. For example:

```
$ wget https://raw.githubusercontent.com/rails/rails/master/actionpack/lib/action_controller/metal/strong_parameters.rb

$ time rubocop -a strong_parameters.rb
...
real	0m4.669s
$ time rubocop -a strong_parameters.rb
...
real	0m1.261s
```

This is on a slower machine so the numbers are a bit worse than the earlier benchmark. Why is the second pass slow? Is that mostly startup costs?

**Comment by gurgeous** [comment]
On the second run, half the execution time is requiring files. I wonder if we should only load cops that support autocorrect. Another optimization would be to avoid loading cops that are explicitly disabled. Also, loading Rack seems to take a large chunk of time from the HttpStatus cop.

**Comment by jonas054** [comment]
> since that mirrors real world usage when plugged into an editor

Do you by that mean that the most common case is that `rubocop -a` doesn't make any changes to the file? That's true. But it's more difficult to solve that case, I believe.

> half the execution time is requiring files

Interesting! How did you measure that?

>  I wonder if we should only load cops that support autocorrect.

That's a big change. We've always let all configured cops report their offenses, running with or without `--auto-correct`. But we could make it configurable I guess. If it turns out to be a big performance boost.

Also... please take a look at my PR. :smile:

**Comment by gurgeous** [comment]
> Do you by that mean that the most common case is that rubocop -a doesn't make any changes to the file? That's true. But it's more difficult to solve that case, I believe.

Yes. When using rubocop via vscode, I might run rubocop -a dozens of times as I'm editing a particular file.

> Interesting! How did you measure that?

I modified `exe/rubocop`:

```ruby
tm = Time.now
require 'rubocop'
printf("%0.3f require\n", Time.now - tm)

require 'benchmark'

cli = RuboCop::CLI.new
result = 0

time = Benchmark.realtime do
  result = cli.run
end
printf("%0.3f cli\n", Time.now - tm)
```

which produces:

```
0.664 require
1.379 cli
```

I'm sure we can find ways to improve startup time if we poke around a bit...

Great work on the PR! Incredible improvement and much appreciated.

**Comment by jonas054** [comment]
I've experimented with caching the compiled node patterns that we get from `def_node_matcher`. This gave a decrease in start-up time by around 15% on my system. I'm not at all sure its worth the effort, because a) it adds complexity, and b) results depend on hardware configuration.

**Comment by ndbroadbent** [comment]
Hi everyone, I've just finished working on [a PR for this `rubocop-daemon` library](https://github.com/fohte/rubocop-daemon/pull/3). I wanted to see if RuboCop could be daemonized, so I searched "rubocop daemon", and found this library! I needed to do a ton of work to make it more reliable and fix a lot of issues, but now it seems to be working really well.

The idea is that this starts RuboCop as a daemon process. A client will connect to the server and send commands, and the daemon will return the results. The default client is a Ruby script, but this also adds some latency. So I've written [a bash script](https://github.com/fohte/rubocop-daemon/blob/5ac6881c0d98d736d27421b8c1516c31b232a226/bin/rubocop-daemon-wrapper) that connects to the TCP server via `netcat`, and it's way faster. This bash script is actually a drop-in replacement for `rubocop`, and it makes it around 20x faster (~150ms to lint/format a file, instead of ~3 seconds.)

It might be a good idea to rewrite this script in Go or Rust, but bash seems fast enough for now.

It was a bit tricky to get it working with VS Code. The [vscode-ruby extension doesn't really allow you to customize the rubocop path or binary](https://github.com/rubyide/vscode-ruby/issues/413). So in the meantime I'm just overriding the binary with a symlink:

```
/Users/ndbroadbent/.rvm/gems/ruby-2.5.3/bin/rubocop -> /usr/local/bin/rubocop-daemon-wrapper
```

I've [added the installation instructions to the README](https://github.com/fohte/rubocop-daemon/blob/aaff4b099f403f550382fe79dc407cd6b27d1a06/README.md#more-speed). (You have to manually download this script and put it in your PATH.)

I've tested this on a few different apps, and I think it should be pretty stable now. But I've only tested on my Mac, and on Ruby 2.5.3. I could use some help testing on Linux, and with different Ruby/RuboCop versions, etc. Please try it out and let me know if you run into any issues!

**Comment by gurgeous** [comment]
Oooh, this looks neat. I'm headed out of town for a few days but I'll try it when I return. This could make a big difference in my workflow.

We should also get a PR going for vscode-ruby to allow customizing the complete path to rubocop. Right now vscode-ruby let's you set a bunch of flags to tweak how rubocop is executed, instead of one string to just specify the entire command line.

**Comment by jonas054** [comment]
I'm closing this issue as I don't think we have any more easy fixes up our sleeves for making RuboCop much faster when invoked from an IDE. It sounds like `rubocop-daemon` is the way forward.
