### ISSUE TITLE
Is autocorrect _actually_ incompatible with parallel?

### ISSUE THREAD

**Issue by searls** [rubocop-hq/rubocop#6495]
Due to an accident in how I'm parsing flags in http://github.com/testdouble/standard, I've been invoking RuboCop with both parallel and autocorrect set without issue. Today, when refactoring, I discovered that the command line options `--parallel` and `--{safe-}auto-correct` will raise an exception when used in combination.  This was added in #4272 along with the `--parallel` flag itself.

in the thread, @cheerfulstoic asked why this was, but @jonas054 replied with an answer about `--auto-gen-config` instead. As far as I can tell, the reasoning wasn't documented anywhere.

Is it possible that this constraint was just an oversight? Would it be safe for `validate_parallel_with_combo_option` to just be removed outright?

**Comment by jonas054** [comment]
@searls You're right, I answered a question about `--auto-correct` by talking about `--auto-gen-config`. Sorry.

When it comes to the `--auto-correct --parallel` combination, it looks like I haven't documented anywhere why that should be illegal. Now I've done some experiments where I've run the two together and I've found that:
1. Files are corrected as they should be, but you can't see that on the console. This is because the corrections are made in the cache warm-up phase, which is silent.
2. Running auto-correction in parallel is only slightly faster than a serial run, if a lot of corrections are made. I got 5.9 vs 7.7 seconds running on the [rails/actioncable](https://github.com/rails/rails/tree/master/actioncable) directory tree with the `--force-default-config` flag.
3. When no corrections can be made, running in parallel is actually slower than a serial run (4.9 vs 4.0 seconds).

**Comment by searls** [comment]
@jonas054 thanks for following up on this. That would certainly validate the fact that I'm also seeing significant slowdowns with `--parallel` enabled.

I feel that either this error/raise should be removed (if it's not actually incompatible/broken) or that the error text should be changed to reflect this. Thoughts?

**Comment by jonas054** [comment]
@searls In my opinion it is a bit broken because information about what has been corrected is lost. But we could change the error message to something like "--parallel can not be combined with --auto-correct because the gain in speed is insignificant". Not sure how we can mention the hidden correction reports. It becomes very technical.
