### ISSUE TITLE
Locking offense count

### ISSUE THREAD

**Issue by faucct** [rubocop-hq/rubocop#6521]
Hello. Does `.rubocop.yml` support offense count limit? For example, you are adding rubocop to existing project, generate a `.rubocop_todo.yml` and want to lock the offense count, so the broken cops would not be disabled, but it would be forbidden to introduce new offenses. I remember that I have seen this feature in other linters, but I can't remember which one exactly.

**Comment by deivid-rodriguez** [comment]
I think https://github.com/rubocop-hq/rubocop/issues/2424 is the same thing, but it also suggests an approach to the problem. I'm happy other people want this! :)

**Comment by siegfault** [comment]
Some of this is alluded to on the issue @deivid-rodriguez linked, but just to sum it all up, what I personally use for this is the combination of `--exclude-limit X --auto-gen-only-exclude` where X is some number higher than the number of files in the repo. The first bit ensures that all files are explicitly listed in the todo (thus adding a new violation would get reported) while the second ensures consistent behavior for the metrics rules.

The one benefit I see to this workaround is that it avoids someone fixing one file and adding a violation to a different file. I believe the proposed solution would allow that reintroduction since the count stayed the same.

Not discouraging adding a feature like this, but I think the workaround works fairly nicely with the admission that the todo file gets pretty big.

**Comment by faucct** [comment]
@siegfault, it looks like `--exclude-limit` is an option for generating `.rubocop_todo.yml`. Can you give me an example of using it preventing offences count increase? Anyway, it looks like this option only counts offensive files, not how much offenses are there.

**Comment by siegfault** [comment]
> Can you give me an example of using it preventing offences count increase?

Oh, yes, sorry. Generating the todo file with that flag is just the first part of preventing violations. The two ways I've then tried to prevent new violations is to use houndci (which comments on the PR, but doesn't flag it in an ongoing fashion so it might be ignored) or write a spec than runs rubocop and ensures there are no violations (which forces the PR author to fix the issue or add to the todo file).

> Anyway, it looks like this option only counts offensive files, not how much offenses are there.

Definitely true for both cases I mentioned above. If there's one violation in a file that gets listed in the todo file, no new offenses will get reported. The whitelist references files rather than offenses. You then have to fix those files to remove them from the whitelist to flag new violations.
