### ISSUE TITLE
How to specify internal DSL methods and others as IgnoredMethods for Style/MethodCallWithArgsParentheses 

### ISSUE THREAD

**Issue by himanshunestaway** [rubocop-hq/rubocop#6564]
https://github.com/rubocop-hq/ruby-style-guide#method-invocation-parens   lays down the guidelines for using parenthesis around method invocation. It is mentioned that parenthesis should be avoided in case of:

1. Method calls with no arguments
2. Methods that are part of an internal DSL (e.g., Rake, Rails, RSpec)
3. Methods that have "keyword" status in Ruby

Currently, I am getting offenses for require, require_relative, include and few other ruby keywords. Also, for rspec keywords such as describe, context etc. Is there a way to have them in the ignored list all at once or as one group each for ruby, rspec, rails etc. instead of specifying one by one.

Ruby version: 2.1.5
Rubocop: 0.49.1

**Comment by Drenmi** [comment]
Unfortunately this cop is not fit to be enabled by default yet. There are just too many false positives at the moment. We are working on it though. Below is outlined, some of the progress:

> Method calls with no arguments.

This is currently handled by another cop.

> Methods that are part of an internal DSL (e.g., Rake, Rails, RSpec)

We try to avoid hard coding knowledge about other libraries in RubuCop. This will be handled through whitelist that can be user populated (current), used by an extension (future) or presets (future.)

> Methods that have "keyword" status in Ruby.

I tried to implement this some time ago. It turned out it's rather hard to get an exhaustive list of things that have "keyword status".
