### ISSUE TITLE
Prevent Style/SafeNavigation

### ISSUE THREAD

**Issue by veganstraightedge** [rubocop-hq/rubocop#6669]
**Is your feature request related to a problem? Please describe.**

As a team (at work), we've decided that the more verbose way is easier to read than the safe navigation way.

Good: `if foo && foo.bar?`
Bad: `if foo&.bar?`

**Describe the solution you'd like**

I would like a cop that I could enable to throw an error when `&.` is used.

**Describe alternatives you've considered**

Maybe this exists? I can't find it in the docs, if it does.

If it's not possible, I'll have to write my own custom cop. I'd rather not. I'd rather _just_ add a rule to our `.rubocop.yml`.

**Comment by rrosenblum** [comment]
Ideally, this would be handled with a configuration in `Style/SafeNavigation`. The default would be to prefer safe navigation with the option to disallow safe navigation. It is easy to identify a method call as safe navigation. 

Keep in mind that there are multiple kinds of auto-corrections to account for.

I think most of the community is moving towards using safe navigation so I personally don't see this as high priority on most people's list to implement. Since you were considering adding a custom cop, I would encourage you to add the functionality directly to RuboCop. There are bound to be other people that would like this functionality as well.

**Comment by mockdeep** [comment]
I'd love to see this. In cases where the shape of objects is known ahead of time, I think `foo && foo.bar` is a code smell, and the safe navigation operator hides that smell without really addressing it. It also tends to get used more liberally than it needs to be.

The reason it is a code smell in my opinion is that `foo` being `nil` can hide a lot of complexity. Why is it `nil`? Is it intentional or accidental? Ideally, we'd find another way of addressing this code that would avoid the check in the first place. Maybe by substituting in a null object that also responds to `bar`, or branching earlier in the code to address the `nil` case more broadly, maybe even with a different controller endpoint.

I'm kind of wondering if there's room for another rule that lints for `foo && foo.bar` checks.
