### ISSUE TITLE
Upgrading 0.64.0 to 0.65.0 causes 'TypeError: superclass mismatch for class Mark'

### ISSUE THREAD

**Issue by henrik** [rubocop-hq/rubocop#6781]
Seems to be related to psych – please see https://github.com/ruby/psych/issues/386 for details.

**Comment by Drenmi** [comment]
Hi, @henrik!

Good to see that you’re staying on top of dependency updates. 🙂

We’ve seen some other problems with Psych on Windows and Ruby 2.6. (https://github.com/ruby/psych/issues/385) What platform and Ruby version are you on?

**Comment by henrik** [comment]
Hi; thanks :)

This is Ruby 2.5.3 and I believe the VMs in CircleCI run on some Linux distro. Let me know if you want the exact one!

**Comment by Jatkins1995** [comment]
@henrik Facing the same problem.  Have you had any luck finding a solution?

**Comment by henrik** [comment]
Hey. Nupe, haven’t done much sleuthing I’m afraid, just locked down Rubocop to an earlier version for now.

Best,
Henrik

**Comment by hirowatari** [comment]
Same issue here.  Using ruby 2.5.3, ubuntu 18.04.  I've locked Rubocop to 0.64.0 to workaround the issue for now.

**Comment by Drenmi** [comment]
@Jatkins1995, @hirowatari Are you both experiencing this problem in CircleCI? Or in your local environment? I have no problem in neither. 😞

**Comment by hirowatari** [comment]
@Drenmi No I'm not using CircleCI.  I'm using a local development environment.

**Comment by erikaxel** [comment]
We also have this issue on our CI. Ruby 2.5.3. It is a docker container based on Ruby which builds on Debian Stretch. I think it is because of this change: https://github.com/rubocop-hq/rubocop/pull/6766/files#diff-458bc38d82061cdac508dfb1be2b918bR41

Is adding psych as a runtime dependency necessary?

**Comment by coldnebo** [comment]
We're having a [similar issue](https://github.com/ruby/psych/issues/386#issuecomment-471050215).  We are using Ruby 2.3.7 currently and Psych 3.1.0 conflicts on Ruby load.  We can't fix it by adding it to our Gemfile.

I'm going to advise locking to rubocop, '0.64.0' to work around this for now.

**Comment by hirowatari** [comment]
Thanks for fixing this!

**Comment by andreaseger** [comment]
Is somebody tracking this issue actually. This is also causing us some headaches using jruby because now it pulls in a maven environment to be able to install psych from source.

Until this gets reverted to use the psych version packaged in the standard lib we cannot update rubocop any longer which is a shame.

If needed I can open a PR which reverts the relevant bits from https://github.com/rubocop-hq/rubocop/pull/6766
