### ISSUE TITLE
NodePattern $... at beginning

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop#6842]
Let's say we have a very simple AST `(send nil :foo)`.

The pattern `($_ ...)` captures `:send`. Good
The pattern `(_ $...)` captures `[nil, :foo]`. Good
The pattern of `($...)` captures also `[nil, :foo]`. Shouldn't it be `[:send, nil, :foo]`?

Note: current behavior is even [in the specs](https://github.com/rubocop-hq/rubocop/blob/master/spec/rubocop/node_pattern_spec.rb#L636-L642) since 358aac6820c

cc @alexdowad

**Comment by alexdowad** [comment]
Hi, @marcandre. I'm just having a look at this.

**Comment by alexdowad** [comment]
Hmm. It's debatable what `$(...)` is "supposed" to do. The code comments say:

    #    '(send $...)'       # capture all the children as an array

I think that `...` was intended for matching the *children* of a node, not the node type. You can also do things like `$_` or `$(send ...)` if you want to capture the entire node, but it doesn't convert it into an array.

If it doesn't break anything, it would be fine to adjust this behavior. Just make sure to add another example in the inline code comments, making it clear what the (new) intended behavior is.

As I have said many times before, the `NodePattern` compiler is very simple and it should be very easy to adjust this behavior. Please have at it.

**Comment by alexdowad** [comment]
Another "solution" would be to make `(...)` illegal, and throw an exception when compiling such a pattern.

**Comment by alexdowad** [comment]
To be honest, I think I prefer the solution whereby `($...)` and `(...)` are treated as illegal. We could implement them... but why? Just more code bloat for a feature which virtually no-one will use.

Less is more.

**Comment by alexdowad** [comment]
> Less is more.

Except when it's not, of course...

**Comment by marcandre** [comment]
> Another "solution" would be to make `(...)` illegal, and throw an exception when compiling such a pattern.

You mean making `...` at the beginning of a sequence illegal? Note my example is simplistic, but there could be more complex uses with an extra term, like `(... :example)`, which would now have to be written as `(_ ... :example)` which seems a bit more complicated for nothing.

**Comment by marcandre** [comment]
Actually, `...` at the beginning of a sequence is not really an issue anyways, it's really just `$...` at the beginning of a sequence that is "strange".

**Comment by alexdowad** [comment]
> You mean making ... at the beginning of a sequence illegal?

Yes.

> Actually, ... at the beginning of a sequence is not really an issue anyways, it's really just $... at the beginning of a sequence that is "strange".

Let me be clear that I don't have a strong opinion either way. At the moment, my preference is to declare `($...)` as illegal, since it wasn't the intended usage and supporting it will mean adding more code. I don't believe that this position is inconsistent or "wrong in principle".

Is `($_ $... :example)` longer than `($... :example)` by 3 characters? Yes. Does that mean we should modify the compiler to support the shorter version? Only if that form is frequently useful. If it's needed once or twice in the whole codebase, then just use `($_ $... :example)`.

Again, I don't have a strong opinion, and I specifically designed `NodePattern` to be easy to modify, so people like @marcandre could add abbreviated syntax for commonly repeated patterns.

**Comment by marcandre** [comment]
This would be very easily changed now, to capture the "symbol" of the node type, or raise. Probably best to keep current behavior until someone shows a good usecase for a different solution, so I'm closing this.
