### ISSUE TITLE
Add feature to suspend a rule based on date of a line's commit

### ISSUE THREAD

**Issue by jayqui** [rubocop-hq/rubocop#7035]
## Is your feature request related to a problem? Please describe.

For a large codebase I'm working with, we are considering introducing a Rubocop rule to discourage a certain behavior, even though the codebase already contains a few hundred violations of the rule we would introduce.

I imagine plenty of teams find themselves in this position.

## Describe the solution you'd like

I'm wondering if Rubocop could have a feature called something like `SkipIfOlderThan`, which might apply a given rule to a line only if it is older than some specified date.. (Not sure how this would work if there is not git-style version control.)

## Describe alternatives you've considered

The only alternative I have thought of is to go into the codebase and flag all 200+ violations, which would be a fairly laborious task.

**Comment by bbatsov** [comment]
We avoid coupling RuboCop to any external tools like git. Generally `--auto-gen-config` is the way to go in situations like the one you've described.

**Comment by scottmatthewman** [comment]
@jayqui In the main project I'm working on right now, we're in the same boat.

We've gone down the route of enforcing good style only on changes. Different devs have different ways of doing this -- I prefer [overcommit](https://github.com/sds/overcommit), as it allows me to differentiate between violations on lines of code I've modified (which I must fix before it'll let me commit them even to my local git repo) and violations present in files I've touched. The latter are treated as warnings, and we will either leave as-is for now, or change in a separate commit and/or PR.

This means that, while we don't have a green RuboCop build, we've taken that to be a true reflection of our code state. It avoids the "lowering of the bar" risk with a `.rubocop_todo.yml` file that can allow new code with the same flaws as the old. 

And while it does mean that it'll take us longer to get to a truly "green" build, I believe it correctly prioritises writing new code to high standards over fretting too much about the old stuff.

**Comment by rrosenblum** [comment]
I have added RuboCop to large old code bases and have felt this pain as well. `--auto-gen-config` works great, but it is a bit simplistic for trying to enforce cops that already have significant offenses in your code. Especially since `--auto-gen-config` will wind up disabling the cop for an entire file or disable the cop entirely if there are offenses in too many files. 

I believe there was a PR several months back that aimed at adding a comment disable configuration that could go through and add `rubocop:disable` comments to offending lines. I don't know what happened to that feature. I don't think it was ever completed. I implemented something similar several years ago by using RuboCop's json output to figure out offending lines and automating adding disable comments.

I think reviving the ability for RuboCop to add disable comments would be the best way of handling this. RuboCop would be able to stay tool agnostic. This would mean making a code change to add all of the comments though.
