### ISSUE TITLE
Feature - Cop to sort rubocop.yml alphabetically

### ISSUE THREAD

**Issue by okuramasafumi** [rubocop-hq/rubocop#7103]
## Is your feature request related to a problem? Please describe.

I'm always annoyed when `.rubocop.yml` entries are not sorted alphabetically.
Sometimes it's not that easy to remember the cop name correctly and it's really helpful to have sorted config file in those cases.

## Describe the solution you'd like

Like `Gemfile`, I think we can sort `.rubocop.yml` alphabetically.

## Describe alternatives you've considered

Nothing particular.

## Additional context

https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/bundler/ordered_gems.rb
The existing `OrderedGem` Cop can give us hints to implement this feature.

**Comment by rrosenblum** [comment]
I agree that would be a nice feature to have. It isn't quite the same as the `OrderedGem` cop because `.rubocop.yml` isn't a Ruby file. I assume that this can be accomplished by fairly easily by loading the yaml file into a hash and then checking the order of the keys. We'll have to come up with some custom ordering to make sure that things like `inherit_from`, `require`, and `AllCops` still show up at the top of the file. It would be great if this scanned files from the `inherit_from` section as well.

**Comment by bbatsov** [comment]
Maybe we can add some extra option (or tiny tool) to lint `.rubocop.yml`?

**Comment by okuramasafumi** [comment]
Maybe this feature should not be a Cop but a command line utility. I'm closing this for now since it's not a RuboCop issue anymore. If you think it should be a Cop then please reopen it.

**Comment by djpowers** [comment]
In case anyone here is still looking for a solution, or if people stumble upon this issue, I recently found the [ruboclean](https://github.com/lxxxvi/ruboclean/) gem which serves as a CLI option to do this.

**Comment by G-Rath** [comment]
I think this would be really useful to have in Rubocop core itself via e.g. `--sort-configuration`, and I think you could even extend it to be a `--clean-configuration` option that could do things like automigrate to `plugins`.

@bbatsov @okuramasafumi is that something you'd be happy to see a PR for, and/or would it be best to re-open this issue, post a new issue, or post a discussion?
