### ISSUE TITLE
FrozenStringLiteralComment Cop

### ISSUE THREAD

**Issue by mullermp** [rubocop-hq/rubocop#7332]
Matz has said that Ruby 3 will not contain frozen string literals ([link](https://bugs.ruby-lang.org/issues/11473#note-53)). Rubocop [still has a cop](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment) that "is designed to help upgrade to after Ruby 3.0". Since this is no longer happening, what is the rubocop team's plan for this Cop? Will it continue to be enforced by default?

**Comment by koic** [comment]
Good catch! The document needs to be updated.

On the other hand, AFAIK, matz has not given up the possibility of defaulting to a frozen string in the future. In Ruby 3.0, matz was abandant for changing it because there were not enough tools to prevent destructive changes(I heard that at RubyKaigi 2019 and RubyConf Taiwan 2019).

Frozen string literals are being introduced around Ruby.

- https://github.com/ruby/ruby/blob/master/lib/erb.rb
- https://github.com/ruby/psych
- https://github.com/ruby/csv
- https://github.com/rubygems/rubygems
- https://github.com/bundler/bundler
- others

So I think that the cop remains enabled by default. I opened a PR #7334.

**Comment by mullermp** [comment]
Thanks for jumping on this. If it were to remain default, I think that the docs should also include some explanation to the benefits of using the frozen string magic comment.

**Comment by rubyFeedback** [comment]
I think they will become the default eventually, but the time frame for ruby 3.0 was too short (it'll be in a bit over a year), so it may happen at e. g. ruby 3.1.

Otherwise I concur - it would create less confusion for users.

> On the other hand, AFAIK, matz has not given up the possibility of defaulting to a frozen string
> in the future.

Agreed. I think it will be revisited after ruby 3.0 has been released, and I think at some point it will indeed become the default, just not for 3.0. We have to wait a bit how things play out; remember that it also has not been long ago before gem+bundler became available in ruby by default, to avoid code-duplication; and the optional static type hint information will also become part of ruby, probably past 3.0, so there will be lots of changes. On a side note, perhaps the gem+bundler situation may be for rubocop too, one day, to become default with ruby releases (I know this may be in the distant future, just mentioning it early on).
