### ISSUE TITLE
Detect zero-width space and similar problematic characters?

### ISSUE THREAD

**Issue by andyw8** [rubocop-hq/rubocop#7445]
We recently ran into an issue where some pasted code resulted in an `undefined local variable or method "\u200B"`. It was within a deploy script so wasn't noticed in development.

(200B is a zero-width space: https://www.fileformat.info/info/unicode/char/200b/index.htm)

Is this something that RuboCop should warn of? Or would it be out of scope?

**Comment by buehmann** [comment]
@andyw8 Can you provide a stripped-down example that shows the issue? It sounds as if the case should be covered by https://docs.rubocop.org/en/stable/cops_naming/#namingasciiidentifiers

**Comment by andyw8** [comment]
Sorry, false alarm. The `Naming/AsciiIdentifiers` cop detects this but but had been disabled for this particular project.

**Comment by Drenmi** [comment]
These are some gnarly errors to deal with. We had a related issue where some SendGrid e-mails always failed to send due to invalid e-mail address, but when checking the address in the console, it looked fine.

Turns out the customer was copy-pasting e-mails from some other application that included a zero-width space when doing so. Took me the better part of one afternoon to get to the root cause. 😂
