### ISSUE TITLE
Revising RuboCop's defaults (survey)

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop#7833]
We're running a [short survey](https://docs.google.com/forms/d/e/1FAIpQLSe3uTB_E164hgGUaM5-DFuIVBgv7l18ub2lAU5gXmw1dw4vPQ/viewform?usp=sf_link) on RuboCop's default prior to releasing version 1.0. 

You can find more details [here](https://metaredux.com/posts/2020/03/27/adjusting-rubocop-s-defaults.html). Thanks in advance for taking the time to share your input with us!

**Comment by lamont-granquist** [comment]
`I use trailing commas in collection literals (e.g. [1, 2, 3,])`

If you meant multiline you should use that word there.  I doubt anyone uses trailing commas in single line, so this question will undercount people who want trailing multiline commas.

**Comment by bbatsov** [comment]
Okay, I'll update the wording there.

**Comment by grncdr** [comment]
An idea regarding the overall process: what would you think about collecting `.rubocop.yml` configs and aggregating stats for which defaults are most often overridden?

**Comment by grncdr** [comment]
I would maybe volunteer to write such a tool if that's of interest to the maintainers.

**Comment by bbatsov** [comment]
@grncdr I think that'd be a super useful tool for us!

**Comment by januszm** [comment]
I think the question about Trailing Commas in Collection Literals was poorly phrased in the survey. The way in which the multi-line variant is presented

```ruby
{ one: 1,
  two: 2, }
```

does not show the advantages of adding this comma. If it were presented like this:

```ruby
{
  one: 1,
  two: 2,
}
```

the result of the poll could vary considerably. Teams using Git / Github should appreciate that adding a trailing comma in the example above will make Git diff more readable and easier to use. This issue was raised in the comments section at https://metaredux.com/posts/2020/05/26/rubocop-defaults-survey-results.html

@bbatsov please have a second look and consider making the trailing comma `only in multi-line literals` default in 1.0 (maybe another survey?)

**Comment by marcandre** [comment]
I'm sorry I missed the survey.
I ❤️ trailing commas too. I use them in all my personal projects. I'm genuinely upset at JSON's creator for not allowing them.

**Comment by bbatsov** [comment]
@januszm I get your point, but I doubt this affected the results significantly. Formatting code in Google Forms is not fun. :-) There won't be any more changes to the defaults before RuboCop 1.0, as I have already committed to this to all of our users.
