### ISSUE TITLE
Is it time to change the name?

### ISSUE THREAD

**Issue by gcentauri** [rubocop-hq/rubocop#8091]
I live and work in the US where protests against police brutality have been ongoing for days, and coming to work this week the word "cop" has an uncomfortable feeling about it. I don't know if this has been discussed before, but out of respect for vulnerable people in the community, it might be worth considering moving away from the name RuboCop.

**Comment by Gmfholley** [comment]
I second this proposal.

**Comment by awolfson** [comment]
I also think this would be the right decision. FactoryBot provides a good precedent, and the feel of the name could even be preserved somewhat by calling it RuboLint or similar.

**Comment by marcandre** [comment]
I wholeheartedly hope that police violence will go down drastically.

I don't feel the best way towards this goal is with blind intolerance for all cops, including virtual ones like RuboCop's. Many policemen are doing their best in difficult conditions. In many countries, cops aren't feared like they can be in some parts of the US. (Disclosure, I'm Canadian)

My hope is that the word "cop" regains the trust of people. I hope the name `RuboCop` remains.

**Comment by bbatsov** [comment]
I sympathise with the situation in the US and I'm truly hoping that the protests will succeed in bringing such much needed changes there (and that we'll see the end of the police violence soon). Still, I'd rather keep politics out of software, as I feel we can't put a stigma on a word due to the actions  of some misguided individuals. I live in a country with a real dictator (although not on paper), unchecked police that's just an instrument in the hands of the government, and while no one here has any fondness of the Bulgarian police as an institution or our cops, I don't have any issues with the words "police" and "cop". The fundamental idea (serve and protect) is great, but the implementation sucks. 

There's also the fact that renaming projects is extremely painful, especially at the scale we're at and will bring a ton of frustration to maintainers of related projects and our end users. 

I hope that everyone will accept RuboCop for what it was meant to be - a fun pun on RoboCop, and not try to charge it with any additional negative meaning. Naming is always hard, but I'm quite fond of the name RuboCop and we won't be changing it.

**Comment by penelopezone** [comment]
Hey @bbatsov I really think you should reconsider this position: 

1. All software is political, and I think we should acknowledge that
2. An association with the cops will cause harm to and otherwise marginalise potential contributors.

**Comment by emilyst** [comment]
> I live in a country with a real dictator (although not on paper), unchecked police that's just an instrument in the hands of the government, and while no one here has any fondness of the Bulgarian police as an institution or our cops, I don't have any issues with the words "police" and "cop".

"works on my machine"

**Comment by veganstraightedge** [comment]
I echo what @penelopezone and @emilyst both said.

1. All software **is** political
2. And even if that wasn't true (it is) and you'd _"rather keep politics out of software"_, then we shouldn't name software after an inherently political force in our society which has _always_ existed to protect white supremacy.[^1]

@bbatsov I urge you to reconsider. A rename is possible. Is it a bumpy transition? Sure. Does that matter in the long run? Of course not! Does anyone remember or care anymore that _Firefox_ was originally named _Phoenix_? Nah. We've moved on with our lives.

RuboCop is still pre-1.0. It's allowed to make API breaking changes. This is that. 

As @awolfson noted above, _FactoryGirl_ to _FactoryBot_ is a great example of prior art.

***

In the meantime, I forked `rubocop` and renamed it to `ruby_lint`.

Here: https://github.com/ruby-lint/ruby_lint
And here: https://rubygems.org/gems/ruby_lint
And here: https://twitter.com/ruby_lint

I will happily hand over all of the those accounts to the Rubocop folks if yall agree to rename `rubocop` to `ruby_lint` (or similar[^2]).

***

1: See: https://crimethinc.com/2017/03/15/slave-patrols-and-civil-servants-a-history-of-policing-in-two-modes
2: `ruby-lint` is abandoned and archived. https://rubygems.org/gems/ruby-lint https://github.com/yorickpeterse/ruby-lint. `ruby-style` is also abandoned https://rubygems.org/gems/ruby-style. `rubylint` is available though. https://rubygems.org/gems/rubylint

**Comment by barmintor** [comment]
If you feel like software isn't political, I recommend that you re-watch the movie that this project is named after - it's plot revolves around corrupt police forces and barriers presented to people seeking justice by software, from algorithmic policing to specifically embodying oppressive political structures in code.

This linter has been valuable for our team - but even conversations in the office note the violence implied by the name. Just think carefully about this, and remember that even Murphy doesn't want to be associated with the name in the end.

**Comment by baweaver** [comment]
I would disagree on the note that software is not political. Facebook and Palantir are key examples of this. Others have phrased this better than me above so I will leave those comments to their merits and instead discuss a few other concerns with the name.

### Cops are Enforcers, not Correctors

The reasons, in addition to the negative connotation of the word "cop", that I would consider changing this is that the gem is inherently a linter and auto-corrector. I don't really think that these align well with RoboCop or the punning to RuboCop.

If we set aside the connotations for a moment a "cop" to me is an enforcer of the law, not necessarily a corrector. Perhaps this is more the role of a guide, a mentor, or something else. The goal of RuboCop is not only in highlighting the rules but providing solutions through autocorrection.

### Code Modification

Perhaps one of the most powerful features of RuboCop is its autocorrect capabilities and NodePattern syntaxes. Neither are immediately discoverable or intuitive when glancing at the name of the gem. 

The sheer amount of surprise I get when I mention autocorrect to other Rubyists is concerning considering how useful it can be. I feel the name can and does hide these capabilities.

### Language Parity

The name, while having uniqueness, will lead to confusion for newer developers looking for a linter, code mod, or other similar tool from other languages. Much as we do when debating features for the Ruby language we take other languages naming conventions and habits into serious consideration. I believe this should be the same for common gem names.

This can present discoverability issues. Consider Net::HTTP vs Typhoeus as an example. One is very easy to find for a lot of other language-fluent developers, the other requires domain knowledge of Ruby tooling. I think Typhoeus is a much better API and enjoy using it over the native one, but the native libraries name is far more accessible when starting from zero.

-----

Now to be abundantly clear I do think the name can be harmful to marginalized communities, and do not mean to discount those points above in the least. I merely wished to highlight other reasons why the name of this gem may not be the best fit for the purposes it serves.

**Comment by johnsyweb** [comment]
[Words matter](https://tools.ietf.org/id/draft-knodel-terminology-00.html). As an industry, we're moving away from words that exclude folks (you can see this, for example, in Rails https://github.com/rails/rails/pull/33681). 

> I'd rather keep politics out of software, as I feel we can't put a stigma on a word due to the actions of some misguided individuals.

As long as _people_ are using software, it will be political. There *is* a stigma on the word, whether we like it or not.

As you prepare for the v1.0 release, now is the ideal time to consider the name of and I encourage you to do so.

**Comment by noahgibbs** [comment]
To echo @barmintor's point, no matter how you feel about policemen in general, the specific movie "Robocop" is clearly using it the word/idea an ominous and oppressive way. If your preferred feeling is "some cops are fine" or "policing in general is fine," your current name is undermining that point.

If you had named the gem "Rubycop", it would be different: it would be about cops in general. The name "Rubocop" is clearly alluding to the movie.

(I'm not suggesting "Rubycop" as a rename.)

I also like @baweaver's point that the code-autocorrect is a powerful enough feature to be worth calling out with a rename. I think he's right on that. The current name makes that surprising.

**Comment by masonjojones** [comment]
I completely understand the idea of changing the name. Especially to those who do not understand the context.

I was down on River Walk in protest of more fair policing, defunding corrupt systems, and for change. However, I find it highly offensive that anyone would even consider trying to change the name of something which was meant for good. Alex Murphy was a good cop who fought against corruption. The same kinds of corruption I am protesting against. If you're fighting to change the name Rubocop which is a pun off of Robocop because it is offensive, and you understand the context of what Robocop symbolized, then you are the very people that we are protesting against.

**Comment by veganstraightedge** [comment]
<img width="311" alt="Screen Shot 2020-06-06 at 7 12 57 PM" src="https://user-images.githubusercontent.com/4361/83958712-d6420d80-a829-11ea-9608-0431174d4cc2.png">

**Comment by purcell** [comment]
There's a lovely idea from Neuro Linguistic Programming that "the meaning of your communication is the response you get, not what you think you said". I'm old enough to somewhat appreciate the cheeky movie reference, and to be aware of that movie's anti-corruption message, but that's not the message many users are getting from the name, and I totally understand why.

This feels like a great opportunity to double down on the Ruby community ethos and get a ton of positive publicity by rebranding. At the same time, let's recognise that the request implies a bunch of time and even some material expense for @bbatsov (registered domain names, doc sites etc. beyond "just" renaming in code), and some help scoping that out would probably be appreciated if the request is to seem actionable.

**Comment by baweaver** [comment]
If there are material costs associated with this I would be glad to help pay them.

**Comment by zspencer** [comment]
I have made a gentle fork of RuboCop called `rbhint`: https://github.com/zspencer/rbhint

My goal here is to support parallel development in a manner that can be safely merged upstream, if at any point @bbatsov decides that it's worth rebranding. I've begun by sprouting a new namespace for `rbhint` and renaming the command line program.

I'm not particularly sure I know _how_ to do a gentle refactor this large; but I'd be curious to hear what some of the folks who know ruby a bit better think about the following plan:

1. Sprout new public classes in the `RbHint` namespace that inherit from or alias the `RuboCop` equivalents
2. Begin to prioritize configuration from `rbhint.yml` files instead of `rubocop.yml`
3. Migrate documentation as appropriate.

Unfortunately, I'm a bit stretched too thin to do too all the work on this, but would be happy to share maintainership with others who are enthusiastic to take on this work.

P.s. Sorry @veganstraightedge - Did not see yours until I had did mine :X. I think there may be some parallels and some subtler differences in that I'd also like to shift the degree of assertiveness that rubocop brings to the table down a bit.

**Comment by avdi** [comment]
RuboCop is a great pun, but the name has always felt a bit authoritarian and oppressive. Especially for a *Ruby* tool.

**Comment by bbatsov** [comment]
Disclaimer: I'm starting to write this at 7 am in my morning, so my thoughts are a bit incoherent.

I wonder how all of you would feel if suddenly a ton of people who haven't done anything for the project appeared here, told you're a horrible person and started bullying you into doing what they want...

For almost a decade I've been doing pro-bono work on the style guides, RuboCop and many related projects, but all of this gets easily forgotten. You come out of nowhere, you vilify me over this, you fork the project without even discussing this idea with our team... Whatever. The US has many issues, but so does the open-source community. If even I wanted to rename the project we're talking about 300+ extensions, usages in tens of thousands of projects, messing up with search results that have been building up for years, etc, and an insane amount of work associated with this. I've made nothing out of RuboCop and now you're adding a huge pile of disappointment and frustration on top of this nothing. 

> This feels like a great opportunity to double down on the Ruby community ethos and get a ton of positive publicity by rebranding. At the same time, let's recognise that the request implies a bunch of time and even some material expense for @bbatsov (registered domain names, doc sites etc. beyond "just" renaming in code), and some help scoping that out would probably be appreciated if the request is to seem actionable.

@purcell It's nice to see you around! You might remember how the rename of nrepl.el to CIDER went down - this meant so much additional work and so many confused people for years, that I'd really don't want to walk this path again. And the funny thing is I'll get a lot of hate either way... A couple of years ago I had to undergo the painful process of renaming a widely used project again (tools.nrepl -> nrepl) and there are still people confused today about why there are two of them, why some deps don't work in some cases and so on. 

Everyone, I understand your frustration very much. I've had my share of political activism, I truly support the cause of the people protesting in the US these days, but I think you've got no idea what you're really asking for. If you hate the name you're obviously free to do whatever you wish. I will only ask you to acknowledge the work our team has been doing for such a long time and be a bit more respectful of our time and efforts. I don't even do much Ruby myself these days, but I'm still dedicating a lot of time to RuboCop, because I love the Ruby community. Seems the feeling is not mutual. 

P.S. I haven't seen RoboCop in a while, but I have a vague recollection he was a good guy, who was fighting against the oppressive system.

**Comment by PhoenixWright** [comment]
Don’t get discouraged because of this nonsense. Your response is appreciated and the new “forks” of this project are nothing more than cruel jokes. Wastes of time. Unbelievable that users would treat this project with such disrespect when they should know exactly what it stands for.

**Comment by zspencer** [comment]
@bbatsov - Hey, I apologize for not being clear. My goal is not to tell you that you should spend a bunch of time and attention renaming rubocop pro-bono. My goal is to step forward and take responsibility for doing what I can to make that path easy for you to take if you so choose.

There are two things here that are true, and I believe that we can find a happy path that bridges the two of them.

First, in the United States of America, the police force may choose to extra judiciously execute people. The probability of them getting away with it is directly related to the color of someone's skin. This is a cold truth. A brutal truth. A truth that cuts so hard that to look at it is to suffer and encourage us to skirt our eyes away and close our minds. And it's a truth that is far worse when experienced.

Second, the effort it takes to rename a project of this size is significant.  Further, it is unreasonable for those of us who _live in the U.S._ and make six-figure plus salaries demand _you_ to do that work. It's a reflection of American imperialism extended into the digital sphere. Your country is not responsible for the United States problem. Your lifestyle is probably not subsidized by the companies that make billions of dollars a year on surveillance.

My goal with my fork of rbhint is _not_ to replace RuboCop, but to do the work to reframe the project for an American reality.  Just like Ubuntu doesn't replace Debian, just reframes it for home use.

If, at some point, you want to merge the whole kit and kaboodle, I intend to make it easy to do so. 

None are free until all are free. 

In Solidarity, Zee

**Comment by colopatiron** [comment]
I am 100% in support of BLM and the protests, but I don't think there's any need to change the name. That would just create too much inconvenience for so little gain.

**Comment by rubyFeedback** [comment]
It's a fun discussion, but not applicable. Lots of people would be confused about a sudden name change.

Different people associate words in different, disparate ways.

+1 for retaining the name rubocop. Rubo, the cop, enforces the styles for use in a particular code base. That makes sense. And while I am totally in favour of US folks transitioning into a fair democracy, the name rubocop has nothing to do with any political movement and should not be attempted to tied down to one. So -1 for the threadstarter from me.

**Comment by ekampp** [comment]
It's really interesting how so many have such strong opinions about what should and should not do. I stand with @bbatsov!

The only single comment in all of this mess being anywhere close to reasonableis @zspencer's. Because he's the only one willing to put anything on the line for a change to happen.

**Comment by execat** [comment]
RuboCop has as much to do with real cops as "photo**cop**y" or "teles**cop**e". It is a smart pun and that's about it.

@bbatsov is right, and I'd hate for the name to change.

**Comment by concept47** [comment]
@bbatsov Thank you for all your hard work on this gem! That cannot be said enough. 

I'm just as clued into the BLM protests as anyone and have been right from when the movement originated after the Trayvon martin and Michael brown shootings. 

I think something that is being subtly missed here is that the aim of the protests is to *reform* Police, to get them to treat us the same way as everyone else, and not to erase them from life, or history. We'll always have police, and we'll always need them ... and we should not be applying the antipathy of current events to a piece of software that has done nothing wrong :) 

More importantly, police Forces all over the world could learn a thing or two from Rubocop. It de-escalates conflict while achieving compliance because we as engineers trust it as a neutral and impartial arbiter of agreed upon standards. Black lives clearly matter to Rubycop! Which is exactly why I think Rubocop should remain the name of this gem. 

cheers all!

**Comment by xiongtx** [comment]
I've appreciated @bbatsov's work for years, so to see a sudden deluge of people who've contributed nothing appear out of the ether w/ the gall to _order_ a project maintainer make a completely nonsensical breaking change is worth at least two sneers & a round of mockery.

It'd be almost funny were it not obviously hurting conscientious maintainers who care way more than they should about keeping a community of infantile finger-pointers happy. It's to be expected that those who do the least demand the most--_c'est la vie_--but when demands turn into cyberbullying, annoying crosses over to execrable.

As far as "cop" is concerned, police keep communities safe and uphold the law. Sometimes they fail to maintain the expected standards when dealing w/ dangerous individuals, for which they should be held accountable, but they remain the thin blue line between civilization & chaos. Moreover, police encounters are made risky by the very criminals whom the proposers of the name switch champion. Yet those who shed crocodile tears for felons seem to simultaneously celebrate the assault of business owners and smashing of shops, many of which are owned by immigrants and low-income families.

<hr/>

I'm going to raise a 🍺 to @bbatsov and all the other maintainers putting in work to create projects enjoyed by thousands. You deserve all the thanks in the world and none of the venom spat by those who've never lifted a finger to give back to the community.

I'm also raising a 🍺 to law enforcement everywhere risking their safety to keep rioters & looters from ruining the lives of the hard-working, law-abiding many. Unfortunately in the real world there's no [Robocop](https://www.youtube.com/watch?v=Z931XZ2wfpE) to give thugs their comeuppance, only men & women who put on a uniform each morning and do their duty on behalf of ingrates who don't know right from wrong.

Finally, I raise a 🍺 to 🇺🇸, my beloved adopted country, for which I came halfway around the world. It's not the first time she's been attacked by goons, and it won't be the last, but no matter the adversity, we will carry the torch of civilization forward, and the 🔥 of liberty shall not perish from this earth!

**Comment by connorshea** [comment]
I think "keeping politics out of software" is impossible, software is ultimately inherently political because it effects people.

That said, I really don't think renaming the project would be particularly useful or worth the significant effort it'd take. I'd be opposed to it.

Thank you @bbatsov for your work on rubocop over the years, and I'm sorry you've had to deal with this today.

**Comment by claudiug** [comment]
and SJW appear...

this is a joke. there is also a lot of problems in the world, beside cops, should we cover also that? and the world is not USA.

let change ruby, because people in africa are being kill, for some rich white asses that needs diamonds.

**Comment by coding-bunny** [comment]
`alias ruby_lint=rubocop` in your `.bashrc`

**Comment by claudiug** [comment]
also see the hypocrisy here
- ICE is using github
- microsoft for decade was trying to kill open source
- you beloved platform to yell to clouds like old men, twitter is promoting agressive behaviour
- usa is selling weapons to anyone that wants
- usa is actively ignoring climate changing
- you are using iphone, that remove software is china ask them
- you totally ignore Chinese oppression against the own people or color people
- you totally ignore indian suppression against muslin.
And then, after decade of ignoring police brutality, blatant ignorance, you decide the best is to change one library. 
For the people that agree with this: fuck off, grow up idiots.

**Comment by ashmaroli** [comment]
This is absurd.. Glad the maintainers did not opt to rename the project.
Whatever stigma is associated with the term *cop* is only temporary and will soon pass..

To those who are advocating the rename, are you all suggesting that:
- if there was a project named *corona*, it should now be renamed to something less traumatizing in the wake of the Covid-19 pandemic?
- Or if in the future a nation was attacked by an extremist group named *R.U.B.Y*, the programming language should be renamed altogether as well??

**Comment by siassaj** [comment]
Hands that help are holier than lips that pray.

If you give a shit about people's circumstances & have time, go volunteer in young women's and teens education.

Making token efforts at "change" in such an absurd way ... word replacementism??? ... is sad.

**Comment by hrvladev** [comment]
This is ridiculous...

The problem isn't in the word "cop".

If you want to make a difference, take a meaningful action.

- Make children and raise them well. Emphasize on good education, a proper believe system and moral values.
- Organize a social event and make an appeal.
- Join a protest.
- etc

But picking on open source projects and demand dropping the "cop" part is just nonsense.
The RuboCop project has nothing to do with the situation in the USA. Here's its mission:

> We're committed to promoting the best Ruby programming practices and helping people write better Ruby applications.

Changing the name won't change the desperate situation in the USA.
You are talking about "uncomfortable feeling" and "respect for vulnerable people in the community".

How changing the name "RuboCop" will make a difference?

---

> Or if in the future a nation was attacked by an extremist group named R.U.B.Y, the programming language should be renamed altogether as well??

Spot on, @ashmaroli

**Comment by carlfranz** [comment]
Idiocracy!

**Comment by carlfranz** [comment]
God bless the thumb democracy.

**Comment by lrz** [comment]
My 2 cents as a long-time rubyist (who hasn't been using ruby much recently).

I kudos you @bbatsov on your stance on keeping politics out of software. (Especially open source projects which need to be inclusive). I also like the project name as is, since it's a pun and I love puns. However, I would like to make 2 points:

1) This is not a political issue. Regardless of where you stand politically speaking, watching these videos online of cops beating people will make you uncomfortable. There is a stigma that associates cops with brutality and violence, it has always been there for minorities and now the whole population sees it as well. I'm writing this from Europe by the way, we have our own share of police brutality over there as well. It's not just the USA, I believe it's a worldwide issue.

2) Your users are clearly affected by this. What is an open source project without users, or without taking care of its users? 

I would recommend to rename the project, however going with something boring like `ruby-linter` isn't a good idea. Why not doing a community contest to pick the next project name? You could enforce a few rules, like "the name must be a pun" etc. You could also invite people from the community to help you decide which pun is better (I know of a certain Mr Patterson who I believe would be of great help). At the end, once you have your new project name, you could re-launch the project and use the opportunity to speak out against police brutality (which again, isn't really a political statement, just something we humans should do).

**Comment by amatsuda** [comment]
ええー、この件、bbatsovとまかんどれの大人力あふれる初期消火コメントを持ってしても止められなかったの？？
すごいな、社会正義を愛してやまない方々は最初から他人の話とか聞く気はいっさい無いんだろうなぁ。
ていうかイギリス人たちがわざわざ寄ってたかって火をくべてるのはいったいなんなの……

**Comment by Ptico** [comment]
I’ve seen a statement “Open Source should not be political” hundred times since 2014 regarding the aggression against Ukraine, where more than 10000 civilians, including kids, have been killed and more than 2 million forced to leave their homes and everything they had. What changed? Have any of you, dear participants, gave a single shit? Can you even find Bulgaria on the map?

GTFO from @bbatsov he doesn’t owe you anything. You owe him

**Comment by sebastian-palma** [comment]
Why should it change now? Just now because you realized something many of us have known long time ago? It seems to me hypocrite for the less.

You might also want to open this issue in [these](https://github.com/search?q=cop) 45.854 repositories currently in Github (you might be ignoring Gitlab, Bitbucket and some others) containing the word "cop" as well @gcentauri.

**Comment by keymone** [comment]
I disagree with everybody supporting the rename. If this means so much to you - stop using the project, fork the repo, do all the work required to change the name and advocate for adoption of your fork. Nobody owes you this, nobody has to feel offended by some word just because you do. Put in some effort or GTFO.

**Comment by cec** [comment]
Congrats @bbatsov  for standing up to these bullying activists that never put a minute of their time in the great RuboCop project!

They are the same people that threatened Linux's future with the dumb and disgusting code of covenant that openly claimed to be against meritocracy!

It's disgusting to read comments claiming that software is political!
Software IS NOT political and never shall be.
OpenSource software is a monument to meritocracy, where merit lies in quality of code and dedicating your time to it for free.

Products can be political and it is done by altering the content and access to your product (I am disgusted by this practice, but you do what you want with your product to indulge the little authoritarian in you, but stay out of other people's work)

**Comment by evrial** [comment]
lmao SJW go eat dogs shit

**Comment by pat** [comment]
The vitriol in this thread is disappointing me greatly.

I don't see anyone _demanding_ the name change, nor _bullying_ others to make a change happen. Those who've asked for this change to happen are requesting politely, explaining their reasons calmly.

And while I don't think 'being a contributor' should be a requirement for people casting their opinions here, let's be clear: I recognise a bunch of folks who are asking for the project's name to be changed as _significant_ contributors to Ruby open source libraries and the community. I've seen them speak or host conferences, lead the development in essential Ruby gems, and strive to make this community and broader industry smarter, more compassionate, and more welcoming. ❤️

I think words matter, I think police brutality is a global issue, I think we should embrace opportunities to make our community _more_ respectful rather than less. There's an opportunity for improvement here, and I think it should be embraced. Much like the original comment by @gcentauri I find myself feeling less and less comfortable using a tool with this name - and that's not a reflection on how useful this gem is, nor a reflection on whether @bbatsov's work is valued. Clearly, people appreciate this gem and what @bbatsov has done, because otherwise they wouldn't be here making a request.

I understand that a name change is not likely. I think that's a shame. I'll certainly be paying attention to alternative libraries.

**Comment by SRGOM** [comment]
As someone who is against abortion, I'm beginning to see a value in it. I mean obviously mothers who want to abort aren't fit to raise a kid and thereby also help the state by not burdening them with nonsense like op and op's supporters

**Comment by sushant12** [comment]
@gcentauri 

u and everybody who wants to rename this project just because there is a cop in the name should be ashamed of yourself. 
I know what you should do. Fork the repo, rename it, and use that.

Dont come here and disrespect a man's years and years of hard work.

**Comment by pat** [comment]
Also, @bbatsov can I request you lock this thread from further comments. You've made your decision, and there are some extremely abusive remarks being added that don't help at all.

**Comment by smudge** [comment]
Yeah, looks like a lot of this anger-pile-on happened because this PR got from linked here about 4.5 hours ago:
https://www.reddit.com/r/ruby/comments/gy6cza/issue_request_on_github_to_rename_rubocop_due_to/

Doesn't feel like this is going to be a very productive conversation at this point. Hey, Redditors, nice to see that you're calm and collected as ever. `</sarcasm>`

**Comment by SRGOM** [comment]
Ive been wondering- why are all sjw women fat and or ugly and/or seriously damaged? Maybe their parents need to be punished for not raising them well. Same goes for effeminate sjw "dudes"

**Comment by tachyons** [comment]
Open source isn't independent of politics. But world isn't America and politics isn't same or subset of American politics. 

If cops are bad in your country/system, fix that system, banning the usage of the word cop is accepting the failure

**Comment by evrial** [comment]
This is what happens when fathers are excommunicated, kids

**Comment by Morozzzko** [comment]
This conversation is going out of hand, yet I'll give my own shot at providing something positive

Please, if you're reading this and you feel like there's a need for a fork of RuboCop, consider joining and supporting other projects, such as [Standard](https://github.com/testdouble/standard). It's a good project, but it needs more momentum.

Being a wrapper around RuboCop, Standard refers to rubocop's docs _a lot_.  With your help, that can change. Improving the ecosystem around Standard will actually allow it to become independent of rubocop. 

Please consider joining an existing cause. I'm also appealing to @veganstraightedge and @zspencer in a hope to join the efforts

**Comment by coding-bunny** [comment]
Perhaps it's best to lock this, as the discussion/conversation is turning toxic for no good reason. The decision was made to not rename the project, and both sides have expressed their views. There really is no need for name-calling people involved in this discussion, as that only increases the heated discussion leading to nowhere.

We all have our views and opinions, but we can still convey them properly.

**Comment by sunny** [comment]
Please also remove the disrespectful comments by @SRGOM and @evrial. They do not represent the Ruby community.

**Comment by evrial** [comment]
@sunny don't offend me excluding from software community

**Comment by SRGOM** [comment]
@sunny, please don't procreate.

**Comment by bbatsov** [comment]
Yeah, I feel that the conversation here stopped being productive, so it's time to lock it. I'll just mention a few closing words:

> Please, if you're reading this and you feel like there's a need for a fork of RuboCop, consider joining and supporting other projects, such as Standard. It's a good project, but it needs more momentum.

I think that's a great suggestion, as Standard has been around for a while.

> My goal with my fork, rbhint, is not to replace RuboCop, but to do the work to reframe the project for an American reality. Just like Ubuntu doesn't replace Debian, just reframes it for home use.

@zspencer Thanks for the explanations! That's fine by me. 

There are many other things I'd like to add, but it seems we have to lock this discussion right away as even as I'm writing this message I see things are getting way out of hand.

**Comment by bbatsov** [comment]
After some consideration I wrote [an article](https://metaredux.com/posts/2020/06/08/the-rubocop-name-drama-redux.html) to bring some closure to the topic.
