### ISSUE TITLE
Should we enable the auto-correct for Layout/LineLength?

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop#9073]
I think we should, as without it the code-formatting abilities of RuboCop stay limited. The auto-correct is far from perfect, but it gets the job done and will simplify the lives of many users IMO.

@rubocop-hq/rubocop-core What do you think?

**Comment by smcommits** [comment]
@bbatsov I think it is an essential feature and I am assuming it won't be very troublesome to implement the solution.

**Comment by marcandre** [comment]
@smcommits auto-correction is already implemented, just not enabled by default.

@bbatsov I don't have a strong opinion either way (rare, I know 😅)

**Comment by bbatsov** [comment]
@marcandre I'll count you in favour then. 😉

**Comment by jonas054** [comment]
I'm also in favor. It's one of those features that many users might not know exist, and can turn off if they disagree.

It's a bit strange that we haven't turned on AutoCorrect locally in rubocop itself. We should have done from the start to get an indication on how safe it is. So that's another option. Turn it on for our own project and test drive it for a while.

But I'm okay with enabling it in default configuration. Either one.

**Comment by bbatsov** [comment]
> It's a bit strange that we haven't turned on AutoCorrect locally in rubocop itself. We should have done that from the start to get an indication on how safe it is. So that's another option. Turn it on for our own project and test drive it for a while.

The problem is we don't have long lines to auto-correct. :D I think there's one other aspect of having this enabled by default - it's going to force innovation there, as more people will become aware of that functionality.
